version: '2'
services:
 workbench:
  build: ./
  image: kilhaasi/workbench
  volumes:
  - $HOME/Documents/plexdrv:/etc/plexdrv
  devices:
  - /dev/fuse
  #ports:
  #- 122:22
  privileged: true
  cap_add:
  - MKNOD
  - SYS_ADMIN
