#!/usr/bin/with-contenv bash
while [ ! -f "/mnt/G-Cache/Video/gocryptfs.conf" ]
do
 echo "Waiting for gocryptfs.conf to appear..."
 sleep 1
done

mkdir -pv /mnt/Video /crypt/output /crypt/input /Video

gocryptfs -passfile /root/.plexdrive/enc-pwd /mnt/G-Cache/Video/ /mnt/Video
cp /mnt/G-Cache/Video/gocryptfs.conf /crypt/output
gocryptfs -passfile /root/enc-pwd /crypt/output /crypt/input
unionfs -o cow /crypt/input=RW:/mnt/Video=RO /Video

until false
do
 true
 sleep 1
done
