#!/usr/bin/with-contenv bash

echo "PATH=$PATH:~/bin" >> /root/.profile
mkdir -pv /root/.plexdrive
cp -v /etc/plexdrv/config.json /root/.plexdrive
cp -v /etc/plexdrv/token.json /root/.plexdrive
cp -v /etc/plexdrv/.rclone.conf /root
cp -v /etc/plexdrv/enc-pwd /root
